var config = {
  style: "map/style.json",
  showMarkers: true,
  markerColor: "#3FB1CE",
  inset: true,
  legend: false,
  theme: "light",
  useCustomLayers: true,
  bookmarks: false,
  chapterReturn: true,
  headerTitle: "15 Years of Community-led Mapping",
  logo: "",
  subtitle:
    "Short blurb to set the stage for the story, and introduce the main theme.",
  byline: "27 November 2024 : Kshitij Raj Sharma",
  welcomeImage: "",
  creditLogos: [""],
  backgroundImage: "images/header-img.png",
  mobileview:
    '<div id="rotate-mobile"><em>For optimal viewing of this storytelling map on mobile, rotate your device to a horizontal orientation.</em><br><br><img src="images/device.png">',
  footer: "Copyright 2024 @ Kshitij Raj Sharma",
  chapters: [
    {
      id: "drive",
      alignment: "left",
      hidden: false,
      title: "When Drive Meets Information",
      image: "",

      description:
        "We live in a world where almost anyone, anywhere can see when disaster strikes around the globe. And most times, with access to this information, comes a feeling of responsibility and wonder—what can I do to help from so far away?",
      location: {
        center: [0, 0],
        zoom: 1,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      spinGlobe: false,
      mapInteractive: true,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],

      descriptionImages: [],
    },
    {
      id: "drive",
      alignment: "right",
      hidden: false,
      title: "",
      image: "",
      // caption: "HXL Logo",
      website: "",
      description:
        "This is the sentiment that brought together a small group of innovators who shared a passion for new, free, and open source mapping technologies like OpenStreetMap (OSM), combined with  a desire to use it to solve humanitarian problems.They began brainstorming ways they could use the geospatial data being contributed by volunteers all around the world, for crisis response. The premise was that since they were so far away, they would offer what they had:information (in the form of satellite images), skills (in the form of adding  landscape features like buildings and roads to OSM’s database)Connections (to other open map enthusiasts and humanitarian organizations)",

      location: {
        center: [10.451526, 51.165691],
        zoom: 4,
        pitch: 0,
        bearing: 0,
      },
      descriptionImages: [
        "images/hxl_example.png",
        "images/hxl_chart.png",
        "images/hxl_method.png",
        "images/ml_for_hxl.png",
        "images/hxl_slider_1.png",
        "images/hxl_slider_2.png",
        "images/hxl_slider_3.png",
        "images/hxl_slider_4.png",
        "images/hxl_slider_5.png",
        "images/hxl_slider_6.png",
        "images/hxl_slider_7.png",
        "images/hxl_slider_8.png",
      ],
      mapAnimation: "flyTo",
      rotateAnimation: false,
      spinGlobe: false,
      mapInteractive: true,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    {
      id: "cods",
      alignment: "left",
      hidden: false,
      title: "Common Operational Datasets (CODs)",
      image: "images/cod_logo.png",
      // caption: "HXL Logo",
      website: "https://cod.unocha.org/",
      description:
        '<strong>Overview:</strong><br>Common Operational Datasets (CODs) are essential, authoritative datasets curated to support humanitarian response. Managed by UN OCHA, CODs provide stable, standardized data on critical information like population distribution and administrative boundaries. They are often verified and standardized, making them a reliable foundation for operational planning.<br><br><strong>Use Case:</strong><br>CODs are invaluable in a situation like an earthquake that disrupts a densely populated urban area. Humanitarian agencies need reliable data on administrative boundaries, population densities, and key infrastructure to prioritize resources and coordinate response efforts. CODs provide:<br>• Population data to assess affected communities.<br>• Administrative boundaries for coordination.<br><a href="https://data.humdata.org/dataset/cod-ps-npl" style="color:black;">Nepal population COD</a><br><a href="https://data.humdata.org/dataset/cod-ab-npl" style="color:black;">Nepal admin boundary COD</a>',
      location: {
        center: [90.356331, 23.684994],
        zoom: 4,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      spinGlobe: false,
      mapInteractive: true,
      descriptionImages: [
        "images/cod.png",
        "images/cod_population_hdx.png",
        "images/cod_admin_boundary.png",
        "images/cod_population.png",
      ],

      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    {
      id: "pcodes",
      alignment: "right",
      hidden: false,
      title: "Place Codes (P-codes)",
      image: "images/pcode.png",
      // caption: "HXL Logo",
      website:
        "https://humanitarian.atlassian.net/wiki/spaces/imtoolbox/pages/222265609/P-codes",
      description:
        '<strong>Overview:</strong> <br>P-codes (Place codes) are unique geographic identification codes, usually represented by combinations of letters and numbers to identify a specific place, point, positional location, or feature on a map or within a database.<br>There is only one P-code per administrative unit.<br><br><strong>Use Case:</strong> <br>The unique ID can be used to differentiate places with the same name.<br>• P-code and names are used in data collection tools (e.g., 3W, RPM).<br>• Used to aggregate data from different sources.<br>• Used as a dimension for analysis (e.g., geographic severity, priority, etc.).<br>• Can be applied to other datasets so that their geographic location is known if it is a spatial file.<br><a href="https://data.humdata.org/dataset/global-pcodes" style="color:black;">Global Pcode dataset</a>',
      location: {
        center: [9.081999, 8.675277],
        zoom: 4,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      spinGlobe: false,
      mapInteractive: true,
      descriptionImages: [
        "images/pcode_detail.png",
        "images/global_pcodes.png",
        "images/global_pcodes_hdx.png",
      ],

      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    {
      id: "hdx",
      alignment: "left",
      hidden: false,
      title: "Humanitarian Data Exchange (HDX)",
      description:
        '<iframe width="100%" height="500px" src="https://www.youtube.com/embed/OXNlc0dnvIs" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p>',
      // image: "images/hxl_method.png",
      // caption: "HXL Logo",
      website: "https://data.humdata.org/",
      location: {
        center: [69.345116, 30.375321],
        zoom: 4,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: false,
      spinGlobe: false,
      mapInteractive: true,
      descriptionImages: ["images/hdx.png"],

      callback: "",
      onChapterEnter: [
        {
          layer: "case-study-layer",
          opacity: 1,
        },
      ],
      onChapterExit: [
        {
          layer: "case-study-layer",
          opacity: 0,
        },
      ],
    },
    {
      id: "case-study",
      alignment: "right",
      hidden: false,
      title: "Example Case Study: Palestine Humanitarian Response",
      // image:"images/",
      image: "images/case-study-map.png",
      // caption: "HXL Logo",
      website: "https://data.humdata.org/group/pse",
      description:
        'For the example case study on November deaths in the Palestine conflict, I used the following data sources: <ul><li><a href="https://data.humdata.org/dataset/palestine-acled-conflict-data" style="color: black;">ACLED Palestine Conflict Data</a></li><li><a href="https://data.humdata.org/dataset/cod-ab-pse" style="color: black;">COD-AB-PSE Dataset</a></li></ul>Example HXL Data: <a href="https://data.humdata.org/dataset/state-of-palestine-refugees" style="color: black;">State of Palestine Refugees Dataset</a>',
      location: {
        center: [-74.297333, 4.570868],
        zoom: 4,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      rotateAnimation: true,
      spinGlobe: true,
      mapInteractive: true,
      descriptionImages: [
        "images/pse.png",
        "images/case-study-conflictdata.png",
        "images/case-study-qgis.png",
        "images/case_study_vector_join.png",
      ],

      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    {
      id: "other-efforts",
      alignment: "left",
      hidden: false,
      title: "Other Efforts",
      // image: "images/healthsites.png",
      // caption: "HXL Logo",
      // website: "https://healthsites.io/",
      description:
        '<strong>Healthsites.io:</strong><br>Healthsites.io is a collaborative platform that aggregates and shares global healthcare location data, improving data availability for disaster response and public health initiatives. <a href="https://healthsites.io/">Healthsites.io</a><br><br><strong>Humanitarian OpenStreetMap Data Model:</strong><br>The Humanitarian OpenStreetMap Data Model, supported by the Humanitarian OpenStreetMap Team (HOT), provides a framework for  structuring openstreetmap data in multiple gis fileformats and attributes to support humanitarian efforts. <a href="https://data.humdata.org/organization/hot">Humanitarian OpenStreetMap Team</a>.  <br> <strong> Armed Conflict Location & Event Data (ACLED) </strong> <br> Armed Conflict Location & Event Data (ACLED) is a disaggregated data collection, analysis, and crisis mapping initiative. ACLED collects information on the dates, actors, locations, fatalities, and types of all reported political violence and protest events around the world. The ACLED team conducts analysis to describe and explore conflict trends.<br> <strong> and perhaps many more .... </strong> ',
      location: {
        center: [30.802498, 26.820553],
        zoom: 4,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      descriptionImages: [
        "images/healthsites.png",
        "images/hotosm_hdx.png",
        "images/acled.png",
      ],

      rotateAnimation: false,
      spinGlobe: false,
      mapInteractive: true,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
    {
      id: "thanks-block",
      alignment: "center",
      hidden: false,
      // title: "Other Efforts",
      image: "images/tehe_end.gif",
      // caption: "HXL Logo",
      // website: "https://healthsites.io/",
      description: '<p style="text-align: center;">Questions?</p>',
      location: {
        center: [-3.435973, 55.378051],
        zoom: 4,
        pitch: 0,
        bearing: 0,
      },
      mapAnimation: "flyTo",
      descriptionImages: ["images/thanks.png"],

      rotateAnimation: true,
      spinGlobe: true,
      mapInteractive: true,
      callback: "",
      onChapterEnter: [],
      onChapterExit: [],
    },
  ],
};
